### ISSUE TITLE
Dice not clearing

### ISSUE THREAD

**Issue by aramis-erak** [RobRendell/gTove#13]
New issue as of this week.
Dice are not clearing nor autoclearing consistentently.

Especially happens when player A rolls, then B rolls before A can clear,  

Once orphaned, those dice remain until the window is reloaded.

We had over 20 instances on 16 Sep, between 1900 Pacific and 2330 Pacific.

**Comment by RobRendell** [comment]
Thanks!  This will be fixed in the next release.

In the meantime, a workaround is to drag the dice to a different position so that they're not obscuring your view of the tabletop.
