### ISSUE TITLE
[Feature Request]Map Rotation

### ISSUE THREAD

**Issue by aramis-erak** [RobRendell/gTove#41]
A number of geomorphic tilesets are available, but as far as I can tell, one has to upload the 4 rotations separately.

**Comment by RobRendell** [comment]
Hi!  You can rotate maps after adding them to a tabletop by clicking/tapping on them and selecting "reposition" from the menu.  All three gestures are supported when repositioning a map - panning will move it horizontally, rotating with the right mouse button or two fingers will rotate it, and zooming with the mouse wheel or pinch zooming will change its elevation.

If you have "grid snap" on, maps will snap to the closest 90° (or the closest 60° for hex maps), which means it doesn't immediately respond visually when you start to rotate.  Turn off grid snap, or rotate further, and you'll see the map rotate.

Perhaps I could try to make the map selection highlight rotate freely even if grid snap is on, so there's immediate visual feedback that the app is responding.  I'll add that to the TODO list.

Hope that helped!

**Comment by aramis-erak** [comment]
It works, but it took me a dozen tries and using the touchscreen instead of the mouse...
